"""scaffold-rejection-<ts>.jsonl writer (Layer 8/9 hardened inline protocol).

Per HANDSHAKE §4 final-paragraph + Layer 8 simplification + Layer 9
2-part-stderr surfacing. The forensic_writer.py SRP-split module is BL-223
deferred; v2.0 writes inline.

Protocol:

- Path: `.harness/observations/scaffold-rejection-<ISO 8601 microsec>.<pid>.jsonl`
  Microsec + pid suffix closes the same-second collision class.
- NO lock: `O_CREAT|O_EXCL|O_WRONLY` is the atomicity guarantee. On
  FileExistsError, retry with `.r2`/`.r3` suffix (max 5 retries; otherwise
  emit JSONL-fallback to stderr).
- File mode: 0o600 via `os.fchmod`.
- ENOENT/EROFS/EACCES/ENOSPC try/except fallback to stderr with
  `JSONL-fallback:` prefix — validation rejection MUST surface even on
  read-only / full filesystems.
- TWO-PART stderr surfacing:
    Part 1 (BEFORE write attempt): `reason:` + §4-rule-specific hint.
    Part 2 (AFTER `O_CREAT|O_EXCL` retry resolves): `log written to: <path>`
    OR `forensic log unavailable; reason captured above`.
  This ordering closes the L9 path-announcement-before-retry race where the
  announced path could differ from the final `.r2`/`.r3` path actually
  written.
- Single `os.write` ≤ 4096 bytes (PIPE_BUF).
- `os.fsync(fd)` + `os.fsync(dirfd)`; F_FULLFSYNC on darwin.
- ALWAYS-WRITTEN: NOT gated by `telemetry: off` — security/forensic events
  trump the analytics opt-out.
- schema_version: "1.0" (strict-policy per OPERATIONS §4 — readers reject
  absent OR unknown via single reason `scaffold_rejection_schema_version_invalid`).
"""
from __future__ import annotations

import errno
import fcntl
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping, TextIO

# Sibling-script imports.
_SCRIPTS = Path(__file__).resolve().parent.parent
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

from pid_identity import get_pid_start_time  # noqa: E402

REJECTION_FILENAME_PREFIX = "scaffold-rejection-"
REJECTION_FILENAME_SUFFIX = ".jsonl"
MAX_LINE_BYTES = 4096
MAX_RETRIES = 5
SCHEMA_VERSION = "1.0"


def _harness_obs_dir(repo_root: Path) -> Path:
    return repo_root / ".harness" / "observations"


def _utc_now_microsec() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H-%M-%S.%fZ")


def _utc_now_iso_sec() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _build_payload(
    *,
    reason: str,
    field_name: str | None,
    seen_version: str | None,
    extra: Mapping[str, Any] | None,
) -> dict:
    payload: dict[str, Any] = {
        "schema_version": SCHEMA_VERSION,
        "reason": reason,
        "timestamp": _utc_now_iso_sec(),
        "pid": os.getpid(),
        "pid_start_time": get_pid_start_time(),
    }
    if field_name is not None:
        payload["field_name"] = field_name
    if seen_version is not None:
        payload["seen_version"] = seen_version
    if extra:
        for k, v in extra.items():
            if k not in payload:
                payload[k] = v
    return payload


# §4-rule-specific hint table — Layer 9 closes path-mismatch by surfacing
# Part 1 BEFORE the forensic-log write attempt.
_REASON_HINTS: dict[str, str] = {
    "version_unsupported": (
        "decision file generated by older or newer plugin version; delete "
        ".launchpad/scaffold-decision.json and re-run /lp-pick-stack to regenerate"
    ),
    "sha256_mismatch": (
        "decision file integrity envelope mismatch — file may have been "
        "tampered with; re-run /lp-pick-stack to regenerate"
    ),
    "nonce_seen": (
        "this decision file's nonce has already been consumed; "
        "re-run /lp-pick-stack to regenerate"
    ),
    "generated_at_expired": (
        "decision file is older than the 4h replay window; re-run "
        "/lp-pick-stack to regenerate"
    ),
    "bound_cwd_realpath_changed_inode_match": (
        "directory was renamed or moved; re-run /lp-pick-stack to re-bind"
    ),
    "bound_cwd_inode_mismatch": (
        "cwd inode (st_dev/st_ino) does not match the decision file — "
        "symlink-swap or volume-remount attack signal; investigate"
    ),
    "bound_cwd_realpath_mismatch": (
        "decision file was generated for a different cwd; re-run "
        "/lp-pick-stack from the project root"
    ),
    "path_traversal": (
        "decision file contains a path-traversal layer; re-generate via "
        "/lp-pick-stack and avoid `..` in layer paths"
    ),
    "unknown_stack_id": (
        "decision file references a stack id absent from scaffolders.yml; "
        "the plugin may be older than the decision file"
    ),
    "rationale_summary_empty": (
        "rationale_summary is empty or all-empty bullets; re-run "
        "/lp-pick-stack with a richer project description"
    ),
    "forbidden_bullet_token": (
        "rationale_summary bullet contains a forbidden token "
        "(URL/HTML/code-fence); re-run /lp-pick-stack"
    ),
    "platform_unsupported_filesystem": (
        "remediation: move .launchpad/ to a local POSIX filesystem "
        "(apfs/ext4/xfs/btrfs/zfs); non-local FS support deferred to v2.1 (BL-218)"
    ),
    "filesystem_readonly": "mount .launchpad/ writable",
    "cwd_state_brownfield": (
        "cwd is brownfield; /lp-scaffold-stack is not applicable. "
        "Use /lp-define instead."
    ),
    "cwd_state_ambiguous": (
        "cwd is ambiguous; refuse to proceed without user confirmation"
    ),
    "scaffold_decision_invalid_json": (
        ".launchpad/scaffold-decision.json could not be parsed as JSON"
    ),
    "scaffold_receipt_already_exists": (
        ".launchpad/scaffold-receipt.json already exists; check for "
        "concurrent invocation or remove and re-run"
    ),
}


def _hint_for_reason(reason: str) -> str:
    return _REASON_HINTS.get(
        reason,
        f"validation-rejection reason: {reason}; see HANDSHAKE §4 for details",
    )


def _write_part_1(reason: str, *, stderr: TextIO) -> None:
    """Part 1: BEFORE forensic-log write attempt — independent of forensic
    success."""
    print(f"reason: {reason}: {_hint_for_reason(reason)}", file=stderr)


def _write_part_2(written_path: Path | None, *, stderr: TextIO) -> None:
    """Part 2: AFTER `O_CREAT|O_EXCL` retry resolves — actual final path."""
    if written_path is not None:
        print(f"log written to: {written_path}", file=stderr)
    else:
        print("forensic log unavailable; reason captured above", file=stderr)


def _try_write_jsonl(target: Path, line: bytes) -> bool:
    """Attempt single O_CREAT|O_EXCL write of `line` to `target`.

    Returns True on success, False on FileExistsError. Re-raises other
    OSErrors so the caller's outer try/except handles ENOENT/EROFS/EACCES/
    ENOSPC fallback.
    """
    fd = os.open(str(target), os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    try:
        try:
            os.fchmod(fd, 0o600)
        except OSError:
            pass
        os.write(fd, line)
        os.fsync(fd)
        if sys.platform == "darwin":
            try:
                fcntl.fcntl(fd, fcntl.F_FULLFSYNC)
            except (OSError, AttributeError):
                pass
    finally:
        os.close(fd)
    return True


def write_rejection(
    repo_root: Path,
    *,
    reason: str,
    field_name: str | None = None,
    seen_version: str | None = None,
    extra: Mapping[str, Any] | None = None,
    stderr: TextIO | None = None,
) -> Path | None:
    """Layer 8/9 hardened inline scaffold-rejection-<ts>.jsonl write.

    Returns the actual path written on success, or None if the forensic
    log was unavailable (filesystem fallback to stderr taken).

    Two-part stderr is emitted in both cases:
      Part 1: reason + hint (BEFORE write).
      Part 2: log path or "unavailable" (AFTER write attempt resolves).
    """
    if stderr is None:
        stderr = sys.stderr

    # Part 1 — fire BEFORE forensic-log write (Layer 9: path-announce-after-retry).
    _write_part_1(reason, stderr=stderr)

    payload = _build_payload(
        reason=reason,
        field_name=field_name,
        seen_version=seen_version,
        extra=extra,
    )
    line = (json.dumps(
        payload,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=True,
        allow_nan=False,
    ) + "\n").encode("utf-8")
    if len(line) > MAX_LINE_BYTES:
        # Truncate would corrupt JSON; emit fallback to stderr.
        print(f"JSONL-fallback: payload exceeds {MAX_LINE_BYTES} bytes",
              file=stderr)
        print(f"JSONL-fallback: {payload}", file=stderr)
        _write_part_2(None, stderr=stderr)
        return None

    # Best-effort makedirs wrapped in try/except per Layer 8 ENOENT crash close.
    try:
        obs = _harness_obs_dir(repo_root)
        obs.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        # ENOENT / EROFS / EACCES / ENOSPC — emit JSONL-fallback to stderr.
        print(f"JSONL-fallback: makedirs failed ({exc.errno}={exc.strerror}): {payload}",
              file=stderr)
        _write_part_2(None, stderr=stderr)
        return None

    base_ts = _utc_now_microsec()
    pid = os.getpid()
    base_name = f"{REJECTION_FILENAME_PREFIX}{base_ts}.{pid}{REJECTION_FILENAME_SUFFIX}"
    written: Path | None = None

    for attempt in range(1, MAX_RETRIES + 1):
        if attempt == 1:
            target = obs / base_name
        else:
            # Retry suffix per Layer 8 simplification: .r2/.r3/...
            target = obs / (base_name + f".r{attempt}")
        try:
            _try_write_jsonl(target, line)
            written = target
            break
        except FileExistsError:
            continue
        except OSError as exc:
            # ENOENT/EROFS/EACCES/ENOSPC — fallback to stderr immediately.
            if exc.errno in (
                errno.ENOENT, errno.EROFS, errno.EACCES, errno.ENOSPC,
            ):
                print(f"JSONL-fallback: write failed ({exc.errno}={exc.strerror}): {payload}",
                      file=stderr)
                break
            # Other OSError: log fallback then surface as part 2.
            print(f"JSONL-fallback: unexpected OSError ({exc}): {payload}",
                  file=stderr)
            break

    if written is not None:
        # Best-effort directory fsync.
        try:
            dirfd = os.open(str(_harness_obs_dir(repo_root)), os.O_RDONLY | os.O_DIRECTORY)
            try:
                os.fsync(dirfd)
            finally:
                os.close(dirfd)
        except OSError:
            pass

    _write_part_2(written, stderr=stderr)
    return written


__all__ = [
    "MAX_LINE_BYTES",
    "MAX_RETRIES",
    "REJECTION_FILENAME_PREFIX",
    "REJECTION_FILENAME_SUFFIX",
    "SCHEMA_VERSION",
    "write_rejection",
]
