"""Phase 5 fixture builder — runtime-generated scaffold-decision.json fixtures.

Per Phase 5 handoff §4.2: each Phase 5 smoke test generates a fresh decision
file at runtime (not from static fixture files), because `sha256`, `nonce`,
`generated_at`, and `bound_cwd` must be fresh per invocation.

Public API (3 functions per handoff §4.2):

  build_decision(stack_combo, cwd, monorepo, *, matched_category_id) -> dict
  write_decision_to_cwd(decision, cwd) -> Path
  write_matching_rationale_md(decision, cwd) -> Path

Reuses `decision_integrity.canonical_hash` and `_scaffold_stack_helpers`'s
ISO-timestamp + bound-cwd helpers so the integrity envelope is produced
exactly the way Phase 3's `decision_validator.validate_decision()` expects.
"""
from __future__ import annotations

import hashlib
import json
import os
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping, Sequence

_SCRIPTS = Path(__file__).resolve().parent.parent
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

from decision_integrity import canonical_hash  # noqa: E402

# Default rationale body — matches the 6 required sections per HANDSHAKE §4
# rule 7 (project-understanding, matched-category, stack, why-this-fits,
# alternatives, notes).
DEFAULT_RATIONALE_BODY = (
    "## project-understanding\n- A greenfield Phase 5 smoke-test scaffold\n\n"
    "## matched-category\n- runtime-generated\n\n"
    "## stack\n- per stack_combo argument\n\n"
    "## why-this-fits\n- chosen by the Phase 5 driver\n\n"
    "## alternatives\n- rejected: alternatives evaluated by /lp-pick-stack\n\n"
    "## notes\n- generated by Phase 5 driver\n"
)

# Default rationale_summary — 6 sections, ≥1 non-empty bullet each. Mirrors
# the shape Phase 3's `decision_validator._validate_rationale_summary()`
# requires.
DEFAULT_RATIONALE_SUMMARY: list[dict[str, Any]] = [
    {"section": "project-understanding",
     "bullets": ["A greenfield Phase 5 smoke-test scaffold"]},
    {"section": "matched-category", "bullets": ["runtime-generated"]},
    {"section": "stack", "bullets": ["per stack_combo argument"]},
    {"section": "why-this-fits", "bullets": ["chosen by the Phase 5 driver"]},
    {"section": "alternatives",
     "bullets": ["rejected: alternatives evaluated by /lp-pick-stack"]},
    {"section": "notes", "bullets": ["generated by Phase 5 driver"]},
]


def _utc_iso_sec() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _bound_cwd_for(cwd: Path) -> dict:
    real = os.path.realpath(str(cwd))
    st = os.stat(real)
    return {"realpath": real, "st_dev": int(st.st_dev), "st_ino": int(st.st_ino)}


def write_matching_rationale_md(
    decision: Mapping[str, Any],
    cwd: Path,
    *,
    body: str = DEFAULT_RATIONALE_BODY,
) -> Path:
    """Write `.launchpad/rationale.md` with bytes whose sha256 matches
    `decision["rationale_sha256"]`.

    Caller must have built `decision` via `build_decision()` with the SAME
    `body` arg (or with the default). The default `body` matches
    `DEFAULT_RATIONALE_BODY`; if the test wants a custom body, pass it
    consistently to both `build_decision()` and this function.
    """
    target = cwd / ".launchpad" / "rationale.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(body, encoding="utf-8")
    actual = hashlib.sha256(body.encode("utf-8")).hexdigest()
    expected = decision.get("rationale_sha256")
    if actual != expected:
        raise ValueError(
            f"rationale_sha256 mismatch: file={actual!r}, decision={expected!r}; "
            f"pass the SAME body to build_decision() and write_matching_rationale_md()"
        )
    return target


def build_decision(
    stack_combo: Sequence[Mapping[str, Any]],
    cwd: Path,
    monorepo: bool = False,
    *,
    matched_category_id: str = "static-blog-astro",
    rationale_body: str = DEFAULT_RATIONALE_BODY,
    rationale_summary: Sequence[Mapping[str, Any]] | None = None,
    nonce: str | None = None,
    generated_at: str | None = None,
    version: str = "1.0",
) -> dict:
    """Build a fully sealed Phase 4 schema decision payload.

    `stack_combo` is the layers array (each entry: stack/role/path/options).
    `cwd` is the realpath whose (st_dev, st_ino) gets baked into bound_cwd —
    the cwd MUST exist by the time this is called.

    The returned dict is canonical-hash sealed (`sha256` field set) and is
    ready to be JSON-serialized into `.launchpad/scaffold-decision.json`.
    """
    if rationale_summary is None:
        rationale_summary = DEFAULT_RATIONALE_SUMMARY

    rsha = hashlib.sha256(rationale_body.encode("utf-8")).hexdigest()

    payload: dict[str, Any] = {
        "version": version,
        "layers": [dict(layer) for layer in stack_combo],
        "monorepo": bool(monorepo),
        "matched_category_id": matched_category_id,
        "rationale_path": ".launchpad/rationale.md",
        "rationale_sha256": rsha,
        "rationale_summary": [dict(s) for s in rationale_summary],
        "generated_by": "/lp-pick-stack",
        "generated_at": generated_at or _utc_iso_sec(),
        "nonce": nonce or uuid.uuid4().hex,
        "bound_cwd": _bound_cwd_for(cwd),
    }
    payload["sha256"] = canonical_hash(
        {k: v for k, v in payload.items() if k != "sha256"},
    )
    return payload


def write_decision_to_cwd(decision: Mapping[str, Any], cwd: Path) -> Path:
    """Write the sealed decision JSON to `<cwd>/.launchpad/scaffold-decision.json`.

    Uses canonical-form JSON (sort_keys + tight separators + ASCII escape) so
    the on-disk bytes match what `decision_integrity.canonical_hash` would
    produce for an equivalent dict.
    """
    target = cwd / ".launchpad" / "scaffold-decision.json"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        json.dumps(
            dict(decision),
            sort_keys=True,
            separators=(",", ":"),
            ensure_ascii=True,
            allow_nan=False,
        ),
        encoding="utf-8",
    )
    return target


def write_first_run_marker(cwd: Path) -> Path:
    """Write an empty `.launchpad/.first-run-marker` file at mode 0o600 via
    `O_CREAT|O_EXCL` (the same protocol `/lp-brainstorm` Phase 0 uses).

    Per HANDSHAKE §1.5 + BL-235: the marker is a positive-presence empty file
    only — no JSON envelope, no sha256, no bound_cwd, no `.first-run-marker.lock`.
    """
    target = cwd / ".launchpad" / ".first-run-marker"
    target.parent.mkdir(parents=True, exist_ok=True)
    fd = os.open(str(target), os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    os.close(fd)
    return target


# Stack-combo presets per Phase 5 handoff §4.3. Each preset matches the
# fixture spec from the test plan §5 lines 314-394.
STACK_COMBOS: dict[str, dict[str, Any]] = {
    "A": {
        "stack_combo": [{
            "stack": "astro", "role": "frontend", "path": "apps/web",
            "options": {"template": "blog"},
        }],
        "monorepo": False,
        "matched_category_id": "static-blog-astro",
    },
    "B": {
        "stack_combo": [{
            "stack": "fastapi", "role": "backend", "path": "services/api",
            "options": {"database": "postgresql"},
        }],
        "monorepo": False,
        "matched_category_id": "manual-override",
    },
    "C": {
        "stack_combo": [
            {"stack": "next", "role": "frontend", "path": "apps/web", "options": {}},
            {"stack": "fastapi", "role": "backend", "path": "services/api",
             "options": {"database": "postgresql"}},
        ],
        "monorepo": True,
        "matched_category_id": "polyglot-next-fastapi",
    },
    "D": {
        "stack_combo": [{
            "stack": "rails", "role": "fullstack", "path": ".",
            "options": {"database": "postgresql"},
        }],
        "monorepo": False,
        "matched_category_id": "manual-override",
    },
    "E": {
        "stack_combo": [
            {"stack": "supabase", "role": "backend-managed", "path": "supabase",
             "options": {}},
            {"stack": "next", "role": "frontend", "path": "apps/web",
             "options": {}},
        ],
        "monorepo": True,
        "matched_category_id": "manual-override",
    },
    "F": {
        "stack_combo": [
            {"stack": "astro", "role": "frontend", "path": "apps/site",
             "options": {"template": "blog"}},
            {"stack": "next", "role": "frontend-dashboard", "path": "apps/dashboard",
             "options": {}},
        ],
        "monorepo": True,
        "matched_category_id": "manual-override",
    },
    "G": {
        "stack_combo": [{
            "stack": "expo", "role": "mobile", "path": "apps/mobile",
            "options": {"template": "blank"},
        }],
        "monorepo": False,
        "matched_category_id": "manual-override",
    },
    "H": {  # Brownfield refusal — same shape as A
        "stack_combo": [{
            "stack": "astro", "role": "frontend", "path": "apps/web",
            "options": {"template": "blog"},
        }],
        "monorepo": False,
        "matched_category_id": "static-blog-astro",
    },
}


__all__ = [
    "DEFAULT_RATIONALE_BODY",
    "DEFAULT_RATIONALE_SUMMARY",
    "STACK_COMBOS",
    "build_decision",
    "write_decision_to_cwd",
    "write_first_run_marker",
    "write_matching_rationale_md",
]
