"""Tests for v2.0.1 BL-244 #3 (PR #41 cycle-12 #3 closure):
brainstorm-summary.md frontmatter validation in lp-pick-stack Step 0.

Pre-fix shape: lp-pick-stack/engine.py only ran the cwd greenfield gate
and never read .launchpad/brainstorm-summary.md, despite lp-pick-stack.md
Step 0 specifying frontmatter validation. A stale or malformed summary
file (e.g., generated by an outdated /lp-brainstorm version, or hand-
edited with bad shape) would be silently ignored.

Post-fix shape: lp_pick_stack.brainstorm_summary_validator.validate_
brainstorm_summary(cwd) is called from engine.Step 0 after the cwd
greenfield gate passes; refuses with brainstorm_summary_invalid_
frontmatter or brainstorm_summary_greenfield_false on rule failure.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pytest

_SCRIPTS = Path(__file__).resolve().parent.parent
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

from lp_pick_stack.brainstorm_summary_validator import (
    BrainstormSummaryError,
    validate_brainstorm_summary,
    validate_frontmatter,
)


def _write_summary(cwd: Path, frontmatter: str, body: str = "# summary\n") -> Path:
    """Write a brainstorm-summary.md with explicit `---` delimiters."""
    lp = cwd / ".launchpad"
    lp.mkdir(parents=True, exist_ok=True)
    path = lp / "brainstorm-summary.md"
    path.write_text(f"---\n{frontmatter}\n---\n\n{body}", encoding="utf-8")
    return path


# --- Happy path ---

def test_valid_greenfield_summary_passes(tmp_path: Path):
    """Well-formed greenfield summary returns silently."""
    _write_summary(
        tmp_path,
        "generated_at: 2026-05-02T14:30:00Z\n"
        "generated_by: /lp-brainstorm\n"
        "greenfield: true\n"
        "cwd_state_when_generated: empty",
    )
    validate_brainstorm_summary(tmp_path)  # no exception


def test_absent_summary_passes(tmp_path: Path):
    """No brainstorm-summary.md = standalone /lp-pick-stack invocation; allowed."""
    validate_brainstorm_summary(tmp_path)  # no exception


# --- Frontmatter shape failures ---

@pytest.mark.parametrize(
    "fm, expect_substr",
    [
        # Missing required key
        ("generated_at: 2026-05-02T14:30:00Z\ngenerated_by: /lp-brainstorm\n"
         "greenfield: true",
         "missing required keys"),
        # generated_at: not ISO Z-suffix
        ("generated_at: 2026-05-02 14:30:00\n"
         "generated_by: /lp-brainstorm\n"
         "greenfield: true\n"
         "cwd_state_when_generated: empty",
         "generated_at"),
        # generated_at: wrong format (date-only)
        ("generated_at: '2026-05-02'\n"
         "generated_by: /lp-brainstorm\n"
         "greenfield: true\n"
         "cwd_state_when_generated: empty",
         "generated_at"),
        # generated_by: wrong value
        ("generated_at: 2026-05-02T14:30:00Z\n"
         "generated_by: /lp-define\n"
         "greenfield: true\n"
         "cwd_state_when_generated: empty",
         "generated_by"),
        # cwd_state_when_generated: invalid enum
        ("generated_at: 2026-05-02T14:30:00Z\n"
         "generated_by: /lp-brainstorm\n"
         "greenfield: true\n"
         "cwd_state_when_generated: hostile",
         "cwd_state_when_generated"),
        # greenfield: string instead of bool
        ("generated_at: 2026-05-02T14:30:00Z\n"
         "generated_by: /lp-brainstorm\n"
         "greenfield: 'true'\n"
         "cwd_state_when_generated: empty",
         "greenfield"),
    ],
)
def test_invalid_frontmatter_refused(tmp_path: Path, fm: str, expect_substr: str):
    _write_summary(tmp_path, fm)
    with pytest.raises(BrainstormSummaryError) as ex:
        validate_brainstorm_summary(tmp_path)
    assert ex.value.reason == "brainstorm_summary_invalid_frontmatter"
    assert expect_substr.lower() in str(ex.value).lower()


def test_missing_opening_delimiter(tmp_path: Path):
    """A summary file without leading `---` block fails."""
    lp = tmp_path / ".launchpad"
    lp.mkdir()
    (lp / "brainstorm-summary.md").write_text(
        "# Project summary\n\nNo frontmatter here.\n",
        encoding="utf-8",
    )
    with pytest.raises(BrainstormSummaryError) as ex:
        validate_brainstorm_summary(tmp_path)
    assert ex.value.reason == "brainstorm_summary_invalid_frontmatter"


def test_missing_closing_delimiter(tmp_path: Path):
    lp = tmp_path / ".launchpad"
    lp.mkdir()
    (lp / "brainstorm-summary.md").write_text(
        "---\ngenerated_at: 2026-05-02T14:30:00Z\n# no closing\n",
        encoding="utf-8",
    )
    with pytest.raises(BrainstormSummaryError) as ex:
        validate_brainstorm_summary(tmp_path)
    assert ex.value.reason == "brainstorm_summary_invalid_frontmatter"


def test_malformed_yaml(tmp_path: Path):
    _write_summary(tmp_path, "generated_at: [unclosed list\ngreenfield: true")
    with pytest.raises(BrainstormSummaryError) as ex:
        validate_brainstorm_summary(tmp_path)
    assert ex.value.reason == "brainstorm_summary_invalid_frontmatter"


# --- Greenfield: false refusal ---

def test_greenfield_false_refused(tmp_path: Path):
    """Well-formed brownfield summary refuses with the dedicated reason."""
    _write_summary(
        tmp_path,
        "generated_at: 2026-05-02T14:30:00Z\n"
        "generated_by: /lp-brainstorm\n"
        "greenfield: false\n"
        "cwd_state_when_generated: brownfield",
    )
    with pytest.raises(BrainstormSummaryError) as ex:
        validate_brainstorm_summary(tmp_path)
    assert ex.value.reason == "brainstorm_summary_greenfield_false"
    assert "/lp-define" in str(ex.value)


# --- Engine integration ---

def test_engine_step0_refuses_invalid_frontmatter(tmp_path: Path):
    """Engine.run_pipeline returns ABORTED with brainstorm_summary_invalid_
    frontmatter when summary frontmatter is malformed."""
    from lp_pick_stack.engine import run_pipeline

    _write_summary(
        tmp_path,
        # Missing generated_by + cwd_state_when_generated
        "generated_at: 2026-05-02T14:30:00Z\n"
        "greenfield: true",
    )
    result = run_pipeline(
        cwd=tmp_path,
        answers={"Q1": "web-app", "Q2": "yes-needed"},
        skip_greenfield_gate=True,  # only test brainstorm-summary path
    )
    assert not result.success
    assert result.reason == "brainstorm_summary_invalid_frontmatter"


def test_engine_step0_refuses_greenfield_false(tmp_path: Path):
    """Engine.run_pipeline returns ABORTED with brainstorm_summary_greenfield_
    false when the well-formed summary says greenfield: false."""
    from lp_pick_stack.engine import run_pipeline

    _write_summary(
        tmp_path,
        "generated_at: 2026-05-02T14:30:00Z\n"
        "generated_by: /lp-brainstorm\n"
        "greenfield: false\n"
        "cwd_state_when_generated: brownfield",
    )
    result = run_pipeline(
        cwd=tmp_path,
        answers={"Q1": "web-app", "Q2": "yes-needed"},
        skip_greenfield_gate=True,
    )
    assert not result.success
    assert result.reason == "brainstorm_summary_greenfield_false"


def test_engine_step0_passes_with_valid_greenfield_summary(tmp_path: Path):
    """Engine.run_pipeline proceeds past Step 0 when the summary is well-formed
    AND greenfield: true (i.e., NO brainstorm-summary error blocks the path)."""
    from lp_pick_stack.engine import run_pipeline

    _write_summary(
        tmp_path,
        "generated_at: 2026-05-02T14:30:00Z\n"
        "generated_by: /lp-brainstorm\n"
        "greenfield: true\n"
        "cwd_state_when_generated: empty",
    )
    result = run_pipeline(
        cwd=tmp_path,
        answers={"Q1": "web-app", "Q2": "yes-needed", "Q4": "typescript-javascript"},
        skip_greenfield_gate=True,
    )
    # The result may or may not succeed depending on whether the answer
    # combination matches a category — what matters here is that we did NOT
    # short-circuit at Step 0 with a brainstorm-summary error.
    assert result.reason not in (
        "brainstorm_summary_invalid_frontmatter",
        "brainstorm_summary_greenfield_false",
    ), f"Step 0 short-circuited with {result.reason!r}: {result.message}"
